# This is a basic workflow to help you get started with Actions

name: test issue comments

# Controls when the workflow will run
on:
  issue_comment:
    types: [created, deleted]


jobs:
  build:
    if: ${{ contains(github.event.comment.body, 'weekly') }}
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo ${{github.event.comment.body}} 
